improvements: batocera-strip-video

diff --git a/plus/usr/bin/batocera-strip-video b/plus/usr/bin/batocera-strip-video
--- a/plus/usr/bin/batocera-strip-video
+++ b/plus/usr/bin/batocera-strip-video
@@ -16,29 +16,39 @@ QUALIDADE=25
 
 ################################################################################
 
-mkdir -p video
+mkdir -p video-striped
+mkdir -p video-original
 
 for FILE in *
 do
-    if [ -f "${FILE}" ]
+    if ! [ -f "${FILE}" ]
     then
-        ffmpeg -y \
-               -i "${FILE}" \
-               -ss 00:00:00.000 \
-               -to 00:00:${TEMPO}.000 \
-               -c:v libx264 \
-               -preset placebo \
-               -crf ${QUALIDADE} \
-               -pix_fmt yuv420p \
-               -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" \
-               -map 0:v:0? \
-               -an \
-               -sn \
-               -map_chapters 0 \
-               -map_metadata 0 \
-               -f mp4 \
-               -threads 0 \
-               "video/${FILE}"
+        continue
+    fi
+
+    if ffmpeg -y \
+              -i "${FILE}" \
+              -ss 00:00:00.000 \
+              -to 00:00:${TEMPO}.000 \
+              -c:v libx264 \
+              -preset placebo \
+              -crf ${QUALIDADE} \
+              -pix_fmt yuv420p \
+              -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" \
+              -map 0:v:0? \
+              -an \
+              -sn \
+              -map_chapters 0 \
+              -map_metadata 0 \
+              -f mp4 \
+              -threads 0 \
+              "video-striped/${FILE}"
+    then
+        mv -f "${FILE}" "video-original"
+    else
+        rm -f "video-striped/${FILE}"
+        echo "ERROR: ${FILE}"
+        break
     fi
 done
 
