improvement in the wine script

diff --git a/plus/opt/Wine/wine b/plus/opt/Wine/wine
--- a/plus/opt/Wine/wine
+++ b/plus/opt/Wine/wine
@@ -177,6 +177,7 @@ function dxvkExport() {
     export DXVK_LOG_LEVEL
     export DXVK_LOG_PATH
     export DXVK_STATE_CACHE_PATH
+    export PBA_ENABLE=0
 
     local FIRST=TRUE
 
@@ -263,6 +264,31 @@ fi
 
 ################################################################################
 
+### PBA
+
+if [ "${PBA_ENABLE}" == '1' ]; then
+    export vblank_mode=0
+    export __GL_SYNC_TO_VBLANK=0
+    export __GL_SHADER_CACHE=1
+    export __GL_SHADER_DISK_CACHE=1
+    export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
+    export __GL_SHADER_DISK_CACHE_PATH=${HOME}/.cache/shader_cache
+    export MESA_GLSL_CACHE_DISABLE=0
+    export MESA_GLSL_CACHE_DIR=${HOME}/.cache/shader_cache
+fi
+
+################################################################################
+
+### DEFAULT VIDEO OPTIMIZATIONS
+
+if [ ! "${PBA_ENABLE}" ] && [ ! "${DXVK}" ]; then
+    export vblank_mode=1
+    export __GL_SYNC_TO_VBLANK=1
+    export PBA_ENABLE=0
+fi
+
+################################################################################
+
 ### DEFAULT PROFILE
 
 SAVE_DIR='/userdata/saves/windows/wine-profiles'
@@ -336,6 +362,14 @@ fi
 ### MANGOHUD
 
 if [ "${MANGOHUD}" == '1' ]; then
+    if [ -z ${MANGOHUD_CONFIGFILE} ]; then
+        if [ -f '/opt/MangoHud/profiles/smarty.conf' ]; then
+            export MANGOHUD_CONFIGFILE=/opt/MangoHud/profiles/smarty.conf
+        else
+            echo 'not found /opt/MangoHud/profiles/smarty.conf'
+            exit 1
+        fi
+    fi
     MANGOHUD_CMD='/opt/MangoHud/mangohud --dlsym'
 fi
 
@@ -378,6 +412,68 @@ function wineWait() {
 
 ################################################################################
 
+### MOSTRA A AJUDA DO WINE COM OPÇÕES EXTRAS DO Batocera.PLUS
+
+function wineHelp() {
+    "${WINE_DIR}/${WINE_BUILD}/bin/wine${WINE_ARCH}" "${@}"
+
+    echo -e '       wine --check-libs             Show missing dependencies\n' \
+            '\n' \
+            '      Environment variables\n' \
+            '\n' \
+            '      DXVK=1                        Enable detault DXVK\n' \
+            '      DXVK=2                        Enable detault DXVK and hud\n' \
+            '      DXVK=3                        Enable legacy DXVK (vulkan 1.1)\n' \
+            '      DXVK=4                        Enable legacy DXVK and hud (vulkan 1.1)\n' \
+            '      DXVK=5                        Enable proton DXVK\n' \
+            '      DXVK=6                        Enable proton DXVK and hud\n' \
+            '\n' \
+            '      PBA_ENABLE=1                  Enable OpenGL optimizations\n' \
+            '\n' \
+            '      WINEFSYNC=1                   Enable FSYNC, improves load times but crashes some games\n' \
+            '      WINEESYNC=1                   Enable ESYNC, improves load times but crashes some games\n'
+}
+
+
+################################################################################
+
+### VERIFICA SE ESTÁ FALTANDO ALGUMA DEPENDENCIA PARA O WINE FUNCIONAR
+
+function wineCheckLibs() {
+    ${WINE_DIR}/${WINE_BUILD}/bin/wineserver -p0
+    ${WINE_DIR}/${WINE_BUILD}/bin/wine${WINE_ARCH} --check-libs 2> /dev/null | grep ': missing'
+
+    # GSTREAMER TEST
+    #gst-launch-1.0-xx videotestsrc ! autovideosink
+    #gst-launch-1.0-xx audiotestsrc ! autoaudiosink videotestsrc ! autovideosink
+    #gst-launch-1.0-xx playbin uri=file:///usr/share/batocera/splash/splash.mp4
+    #gst-launch-1.0-xx --gst-debug-level=0
+
+    if [ "${WINE_ARCH}" == 64 ]; then
+        wineWait
+        exit 0
+    fi
+
+    for DEP in lib32 \
+               lib64 \
+               lib32/gstreamer-1.0 \
+               lib64/gstreamer-1.0 \
+               lib32/mpg123 \
+               lib64/mpg123 \
+               ${WINE_BUILD}/bin \
+               ${WINE_BUILD}/lib32 \
+               ${WINE_BUILD}/lib64 \
+               ${WINE_BUILD}/lib32/wine \
+               ${WINE_BUILD}/lib64/wine \
+               ${WINE_BUILD}/lib32/wine/fakedlls \
+               ${WINE_BUILD}/lib64/wine/fakedlls
+    do
+        ldd ${WINE_DIR}/${DEP}/* 2> /dev/null | grep 'not found'
+    done
+}
+
+################################################################################
+
 ### START WINE NORMALLY
 
 if [ -f "${WINEPREFIX}/.update-timestamp" ]; then
@@ -387,7 +483,10 @@ if [ -f "${WINEPREFIX}/.update-timestamp" ]; then
     if [ "${WINE_VERSION}" == "${WINE_VERSION_NEW}" ]; then
         case "${@}" in
             --version|--help)
-                "${WINE_DIR}/${WINE_BUILD}/bin/wine${WINE_ARCH}" "${@}"
+                wineHelp
+                ;;
+            --check-libs)
+                wineCheckLibs
                 ;;
             *)
                ${WINE_DIR}/${WINE_BUILD}/bin/wineserver -p0
@@ -534,29 +633,6 @@ exec "${WINE_BUILD}" "${@}"
 # export XDG_DATA_DIRS="/usr/share/:${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
 # export GSETTINGS_SCHEMA_DIR="/wine-staging/share/glib-2.0/schemas:${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
 # export GSETTINGS_SCHEMA_DIR="/usr/share/glib-2.0/schemas:${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
-
-# GSTREAMER TEST
-#gst-launch-1.0-xx videotestsrc ! autovideosink
-#gst-launch-1.0-xx audiotestsrc ! autoaudiosink videotestsrc ! autovideosink
-#gst-launch-1.0-xx playbin uri=file:///userdata/meu_video.wmv
-#gst-launch-1.0-xx --gst-debug-level=0
-
-# WINE DEPS
-#${WINE_DIR}/${WINE_BUILD}/bin/wine${WINE_ARCH}      --check-libs | grep ': missing'
-#ldd ${WINE_DIR}/${WINE_BUILD}/bin/*                 2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib32/*                             2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib32/gstreamer-1.0/*               2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib32/mpg123/*                      2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/${WINE_BUILD}/lib32/*               2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/${WINE_BUILD}/lib32/wine/*          2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/${WINE_BUILD}/lib32/wine/fakedlls/* 2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib64/*                             2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib64/gstreamer-1.0/*               2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib64/mpg123/*                      2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/lib64/*                             2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/${WINE_BUILD}/lib64/*               2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/${WINE_BUILD}/lib64/wine/*          2> /dev/null | grep 'not found'
-#ldd ${WINE_DIR}/${WINE_BUILD}/lib64/wine/fakedlls/* 2> /dev/null | grep 'not found'
 
 # MIDI
 # Set the MIDI (sequencer) device. Default /dev/sequencer.
